export const initialParticipants = [
    // INFO FILLEULS
    { name: "Abiba Fofana", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Abiba Fofana.jpg') },
    { name: "Amadou oury Bah", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Amadou oury Bah.jpg') },
    { name: "Ange-emmanuel Traore", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Ange-emmanuel Traore.jpg') },
    { name: "Bruno Gnanago", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Bruno Gnanago.png') },
    { name: "DAKOI", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/DAKOI.jpeg') },
    { name: "Daniel N_guessan", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Daniel N_guessan.jpg') },
    { name: "Darryl charo pas", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Darryl charo pas.jpeg') },
    { name: "Dominique Maizan", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Dominique Maizan.jpg') },
    { name: "EDEN", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/EDEN.jpg') },
    { name: "GIOVANI", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/GIOVANI.jpeg') },
    { name: "GRAMBOUTE Mohamed", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/GRAMBOUTE Mohamed.jpeg') },
    { name: "Grace N. B. Peters", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Grace N. B. Peters.jpg') },
    { name: "Habib Zoro bi", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Habib Zoro bi.jpeg') },
    { name: "Henih moh Soundele konan", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Henih moh Soundele konan.jpeg') },
    { name: "Hicham KARIMOU", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Hicham KARIMOU.jpg') },
    { name: "Yoram Adje", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/IMG_1075 - Yoram Adje.jpeg') },
    { name: "Issiaka Doumbia", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Issiaka Doumbia.jpeg') },
    { name: "Jamesetta J. Sando", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Jamesetta J. Sando.jpg') },
    { name: "Jean Michel Zoh", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Jean Michel Zoh.jpg') },
    { name: "Jonathan", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Jonathan.jpeg') },
    { name: "Josiah G Flomo", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Josiah G Flomo.jpg') },
    { name: "Kader Bamba", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Kader Bamba.jpg') },
    { name: "Kim Adon", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Kim Adon.png') },
    { name: "Louis Michel Kabran", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Louis Michel Kabran.png') },
    { name: "OJOAWO TIMOTHEE", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/OJOAWO TIMOTHEE.jpeg') },
    { name: "Soro Ben", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Soro Ben.jpeg') },
    { name: "Valdes Kouassi", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/Valdes Kouassi.jpg') },
    { name: "michel soro", role: "FILLEUL", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Filleuls/michel soro.jpg') },

    // INFO PARRAINS
    { name: "Adam Diaby", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Adam Diaby.jpg') },
    { name: "Ado Osee", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Ado Osee.jpeg') },
    { name: "Adou", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Adou.jpg') },
    { name: "Bakary Zie Ouattara", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Bakary Zie Ouattara.jpg') },
    { name: "Basti Oyewumi", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Basti Oyewumi.jpg') },
    { name: "Dountche Issa Kone", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Dountche Issa Kone.jpg') },
    { name: "Elyse Bahoua", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Elyse Bahoua.jpeg') },
    { name: "Goodboi Kallon", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Goodboi Kallon.jpg') },
    { name: "Joseph Komi", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Joseph Komi.jpg') },
    { name: "Joshua D Jarkar", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Joshua D Jarkar.jpg') },
    { name: "Kimberly Gnimadi", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Kimberly Gnimadi.jpg') },
    { name: "Kouame Israel", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Kouame Israel.jpeg') },
    { name: "Manou Ediawo", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Manou Ediawo.jpg') },
    { name: "Rasaq Ilhyas", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Rasaq Ilhyas.jpg') },
    { name: "Sibah Christ Y. Anoman", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/Sibah Christ Y. Anoman.jpeg') },
    { name: "hassou TOURE", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/hassou TOURE.jpg') },
    { name: "sekou coulibaly", role: "PARRAIN", speciality: "INFO", image: require('../assets/INFO image+Nom/Info Parrain/sekou coulibaly.jpg') },

    // EIT FILLEULS
    { name: "CISSE YAYA", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/CISSE YAYA.jpeg") },
    { name: "Coulibaly Zi", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Coulibaly Zi.jpeg") },
    { name: "DIANE Larissa", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/DIANE Larissa.jpeg") },
    { name: "FOFANA Mamadou Junior", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/FOFANA Mamadou Junior.jpeg") },
    { name: "KABORE ISSA", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/KABORE ISSA.jpeg") },
    { name: "KEUMAHON Jean Jacque", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/KEUMAHON Jean Jacque.jpeg") },
    { name: "KOFFI NGUESSAN RAOUL", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/KOFFI NGUESSAN RAOUL.jpeg") },
    { name: "Kangah kouakou", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Kangah kouakou.jpeg") },
    { name: "Kon Hamed", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Kon Hamed.jpeg") },
    { name: "Kouassi Famien", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Kouassi Famien.jpeg") },
    { name: "NDA MARVINE", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/NDA MARVINE.jpeg") },
    { name: "NGBESSO christ uriel junior", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/NGBESSO christ uriel junior.jpeg") },
    { name: "OUATTARA ABDALLAH", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/OUATTARA ABDALLAH.jpeg") },
    { name: "Ochou Emmanuel", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Ochou Emmanuel.jpeg") },
    { name: "Ouattara Cheick", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Ouattara Cheick.jpeg") },
    { name: "Sagnon Justin", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Sagnon Justin.jpeg") },
    { name: "Serme issouf", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Serme issouf.jpeg") },
    { name: "Sorho Donaporgo David-Paul", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Sorho Donaporgo David-Paul.jpeg") },
    { name: "TOURE Kader", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/TOURE Kader.jpeg") },
    { name: "Ti Armel Aim", role: "FILLEUL", speciality: "EIT", image: require("../assets/EIT Image+Nom/Filleul EIT/Ti Armel Aim.jpeg") },

    // EIT PARRAINS
    { name: "Anon Lorraine Maria Florine", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/Anon Lorraine Maria Florine.jpeg') },
    { name: "Coulibaly Kolo Matosso", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/Coulibaly Kolo Matosso.jpeg') },
    { name: "DEMBELE Mohamed", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/DEMBELE Mohamed.jpeg') },
    { name: "DIOMANDE VAKARAMOKO", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/DIOMANDE VAKARAMOKO.jpeg') },
    { name: "DIXON Paxine", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/DIXON Paxine.jpeg') },
    { name: "KPRIE Marie Aime", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/KPRIE Marie Aime.jpeg') },
    { name: "Lanseu Obed Aurel Trsor", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/Lanseu Obed Aurel Trsor.jpeg') },
    { name: "MANLEY George", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/MANLEY George.jpeg') },
    { name: "SANOGO Aminata", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/SANOGO Aminata.jpeg') },
    { name: "SIDIBE ALI", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/SIDIBE ALI.jpeg') },
    { name: "SIDIBE Samira", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/SIDIBE Samira.jpeg') },
    { name: "SYLLA Assita", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/SYLLA Assita.jpeg') },
    { name: "ZRA BI", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/ZRA BI.jpeg') },
    { name: "kEKEMO Coralie", role: "PARRAIN", speciality: "EIT", image: require('../assets/EIT Image+Nom/Parrain EIT/kEKEMO Coralie.jpeg') },
];
